2019-08-15 01:05:08,138  SIGNIN SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:08,211  USE CACHE IN TXT!  
2019-08-15 01:05:09,227  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:09,326  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:48,728  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:48,933  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:50,535  SIGNIN AIRLINE SUCCESS SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:06,572  SUCCESS get_price_itinerary AIRLINE SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:12,572  SUCCESS get_fare_rules AIRLINE SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:13,127  SUCCESS sell_journeys AIRLINE SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:27,492  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:06:27,561  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:06:28,397  SIGNIN AIRLINE SUCCESS SIGNATURE 64ee40a68cd74b9588c5942c7aa3ef85  
2019-08-15 01:07:05,143  SUCCESS get_price_itinerary AIRLINE SIGNATURE 64ee40a68cd74b9588c5942c7aa3ef85  
2019-08-15 01:07:11,721  SUCCESS get_fare_rules AIRLINE SIGNATURE 64ee40a68cd74b9588c5942c7aa3ef85  
2019-08-15 01:08:34,876  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:08:34,946  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:08:35,624  SIGNIN AIRLINE SUCCESS SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:08:50,523  SUCCESS get_price_itinerary AIRLINE SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:08:59,265  SUCCESS sell_journeys AIRLINE SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:09:01,928  SUCCESS get_fare_rules AIRLINE SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:10:34,315  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:34,539  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:35,093  SIGNIN AIRLINE SUCCESS SIGNATURE 7eb7f12977ad46bb9c7a42958eb88b7b  
2019-08-15 01:10:52,144  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:52,436  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:52,953  SIGNIN AIRLINE SUCCESS SIGNATURE 793381fc69d4430383d96ff13395195b  
2019-08-15 01:12:13,662  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:12:13,892  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:12:14,373  SIGNIN AIRLINE SUCCESS SIGNATURE 46b3f3bbe85c4f5a949dff45d2fb86fd  
2019-08-15 01:14:22,721  SIGNIN SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:22,769  USE CACHE IN TXT!  
2019-08-15 01:14:26,022  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:26,313  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:41,186  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:41,387  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:41,613  SIGNIN AIRLINE SUCCESS SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,389  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,406  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,546  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,563  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,675  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,913  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:43,008  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:43,056  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:43,063  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:49,909  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:50,068  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:51,131  SIGNIN AIRLINE SUCCESS SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:06,725  SUCCESS get_price_itinerary AIRLINE SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:14,195  SUCCESS sell_journeys AIRLINE SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:21,170  SUCCESS get_fare_rules AIRLINE SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:53,214  SIGNIN AIRLINE SUCCESS SIGNATURE 27bf33517437483d93eff1aad19f15ae  
2019-08-15 01:15:53,215  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:53,337  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:55,580  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:55,639  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:55,736  SIGNIN AIRLINE SUCCESS SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:16:23,494  SUCCESS get_price_itinerary AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:16:23,521  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,545  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,566  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,587  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,609  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,629  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,647  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,665  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,683  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,704  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,724  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,742  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,757  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,771  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,786  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,801  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,816  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,830  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,842  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,853  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,866  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,878  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,887  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,899  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,912  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,920  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,932  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,947  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,955  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,965  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,976  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:17:07,768  SUCCESS get_price_itinerary AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:17:14,043  SUCCESS get_fare_rules AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:17:51,210  SUCCESS sell_journeys AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:18:20,847  get_balance SUCCESS SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 02:18:58,602  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 02:21:09,262  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 02:21:09,267  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 02:21:48,557  SIGNIN AIRLINE SUCCESS SIGNATURE 06ffa385a1374f74b4e36c160f61b801  
2019-08-15 02:21:48,595  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 02:21:48,609  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 02:21:48,824  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE 06ffa385a1374f74b4e36c160f61b801  
2019-08-15 02:24:18,367  get_balance SUCCESS SIGNATURE 06ffa385a1374f74b4e36c160f61b801  
2019-08-15 02:27:19,217  get_balance SUCCESS SIGNATURE 06ffa385a1374f74b4e36c160f61b801  
2019-08-15 02:30:56,247  get_balance SUCCESS SIGNATURE 06ffa385a1374f74b4e36c160f61b801  
2019-08-15 02:34:39,511  get_balance SUCCESS SIGNATURE 06ffa385a1374f74b4e36c160f61b801  
2019-08-15 02:36:56,549  SIGNIN AIRLINE SUCCESS SIGNATURE 616eab1904ee4d05a689d30e3bd1ac1a  
2019-08-15 02:39:26,570  get_balance SUCCESS SIGNATURE 616eab1904ee4d05a689d30e3bd1ac1a  
2019-08-15 02:41:57,849  get_balance SUCCESS SIGNATURE 616eab1904ee4d05a689d30e3bd1ac1a  
2019-08-15 02:43:01,141  'str' object has no attribute 'update'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 426, in get_price_itinerary
    segment.update({
AttributeError: 'str' object has no attribute 'update'
  
2019-08-15 02:44:28,625  get_balance SUCCESS SIGNATURE 616eab1904ee4d05a689d30e3bd1ac1a  
2019-08-15 02:46:50,209  'str' object has no attribute 'update'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 426, in get_price_itinerary
    segment.update({
AttributeError: 'str' object has no attribute 'update'
  
2019-08-15 02:46:58,688  get_balance SUCCESS SIGNATURE 616eab1904ee4d05a689d30e3bd1ac1a  
2019-08-15 02:47:40,614  SUCCESS get_price_itinerary AIRLINE SIGNATURE 616eab1904ee4d05a689d30e3bd1ac1a  
2019-08-15 02:47:50,828  SUCCESS get_fare_rules AIRLINE SIGNATURE 616eab1904ee4d05a689d30e3bd1ac1a  
2019-08-15 02:49:30,658  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 93, in get_balance
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 02:51:52,603  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 117, in get_transactions
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 02:51:52,608  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 93, in get_balance
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 02:51:53,186  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 134, in login
    request.session['airline_signature'] = res['result']['response']['signature']
KeyError: 'result'
  
2019-08-15 02:54:31,259  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 93, in get_balance
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 02:54:31,261  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 117, in get_transactions
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 02:54:31,621  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 134, in login
    request.session['airline_signature'] = res['result']['response']['signature']
KeyError: 'result'
  
2019-08-15 02:54:43,175  SIGNIN AIRLINE SUCCESS SIGNATURE 7892d956b32f4349b938f55ed300a787  
2019-08-15 02:55:01,658  SUCCESS get_price_itinerary AIRLINE SIGNATURE 7892d956b32f4349b938f55ed300a787  
2019-08-15 02:55:11,371  SUCCESS get_fare_rules AIRLINE SIGNATURE 7892d956b32f4349b938f55ed300a787  
2019-08-15 02:57:11,326  SIGNIN AIRLINE SUCCESS SIGNATURE 7c99298d05dc4ad1be6f775397773dc7  
2019-08-15 02:57:26,651  SUCCESS get_price_itinerary AIRLINE SIGNATURE 7c99298d05dc4ad1be6f775397773dc7  
2019-08-15 02:57:35,266  SUCCESS get_fare_rules AIRLINE SIGNATURE 7c99298d05dc4ad1be6f775397773dc7  
2019-08-15 02:58:17,137  SIGNIN AIRLINE SUCCESS SIGNATURE 7e420b69e5904c9487ac4baf7dbcdaf1  
2019-08-15 02:58:34,687  SUCCESS get_price_itinerary AIRLINE SIGNATURE 7e420b69e5904c9487ac4baf7dbcdaf1  
2019-08-15 02:58:41,924  SUCCESS get_fare_rules AIRLINE SIGNATURE 7e420b69e5904c9487ac4baf7dbcdaf1  
2019-08-15 02:59:04,348  SIGNIN AIRLINE SUCCESS SIGNATURE 9a999bec9b994806844ddc7c62370825  
2019-08-15 02:59:44,265  SUCCESS get_price_itinerary AIRLINE SIGNATURE 9a999bec9b994806844ddc7c62370825  
2019-08-15 02:59:49,441  SUCCESS get_fare_rules AIRLINE SIGNATURE 9a999bec9b994806844ddc7c62370825  
2019-08-15 03:01:19,424  SIGNIN AIRLINE SUCCESS SIGNATURE 9d290c498a6641628fc9fe500725e5a5  
2019-08-15 03:01:20,849  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE 9d290c498a6641628fc9fe500725e5a5  
2019-08-15 03:01:38,259  SUCCESS get_price_itinerary AIRLINE SIGNATURE 9d290c498a6641628fc9fe500725e5a5  
2019-08-15 03:01:55,098  SUCCESS get_fare_rules AIRLINE SIGNATURE 9d290c498a6641628fc9fe500725e5a5  
2019-08-15 03:03:49,110  get_balance SUCCESS SIGNATURE 9d290c498a6641628fc9fe500725e5a5  
2019-08-15 03:04:15,183  SIGNIN AIRLINE SUCCESS SIGNATURE 87689387988946b8ad22ccce8c1bdf63  
2019-08-15 03:04:24,580  SUCCESS get_price_itinerary AIRLINE SIGNATURE 87689387988946b8ad22ccce8c1bdf63  
2019-08-15 03:04:32,348  SUCCESS get_fare_rules AIRLINE SIGNATURE 87689387988946b8ad22ccce8c1bdf63  
2019-08-15 03:06:44,388  get_balance SUCCESS SIGNATURE 87689387988946b8ad22ccce8c1bdf63  
2019-08-15 03:06:49,155  SIGNIN AIRLINE SUCCESS SIGNATURE 5690a9cdab31499696adfd9e2303e344  
2019-08-15 03:06:49,321  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE 5690a9cdab31499696adfd9e2303e344  
2019-08-15 03:06:56,317  SUCCESS get_price_itinerary AIRLINE SIGNATURE 5690a9cdab31499696adfd9e2303e344  
2019-08-15 03:07:02,144  SUCCESS get_fare_rules AIRLINE SIGNATURE 5690a9cdab31499696adfd9e2303e344  
2019-08-15 03:07:24,987  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:07:37,150  SIGNIN AIRLINE SUCCESS SIGNATURE 75a06756db504a869c6522851379c0c9  
2019-08-15 03:07:48,029  SUCCESS get_price_itinerary AIRLINE SIGNATURE 75a06756db504a869c6522851379c0c9  
2019-08-15 03:07:53,960  SUCCESS get_fare_rules AIRLINE SIGNATURE 75a06756db504a869c6522851379c0c9  
2019-08-15 03:08:10,494  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:08:13,357  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:08:13,381  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:08:30,834  SIGNIN AIRLINE SUCCESS SIGNATURE 80b5c0187b4646c18ec43723f0f53a81  
2019-08-15 03:09:08,360  SUCCESS get_price_itinerary AIRLINE SIGNATURE 80b5c0187b4646c18ec43723f0f53a81  
2019-08-15 03:09:28,335  SUCCESS get_fare_rules AIRLINE SIGNATURE 80b5c0187b4646c18ec43723f0f53a81  
2019-08-15 03:09:30,932  SUCCESS sell_journeys AIRLINE SIGNATURE 80b5c0187b4646c18ec43723f0f53a81  
2019-08-15 03:24:20,532  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:24:28,961  SIGNIN AIRLINE SUCCESS SIGNATURE ab16069f96ba4c8b8fa1c5c1cfaf26bc  
2019-08-15 03:24:30,431  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE ab16069f96ba4c8b8fa1c5c1cfaf26bc  
2019-08-15 03:24:39,746  SUCCESS get_price_itinerary AIRLINE SIGNATURE ab16069f96ba4c8b8fa1c5c1cfaf26bc  
2019-08-15 03:24:45,991  SUCCESS sell_journeys AIRLINE SIGNATURE ab16069f96ba4c8b8fa1c5c1cfaf26bc  
2019-08-15 03:24:48,576  SUCCESS get_fare_rules AIRLINE SIGNATURE ab16069f96ba4c8b8fa1c5c1cfaf26bc  
2019-08-15 03:25:09,838  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:25:23,013  SIGNIN AIRLINE SUCCESS SIGNATURE 314874dc87cd4676894cd03481a9ea22  
2019-08-15 03:25:33,295  SUCCESS get_price_itinerary AIRLINE SIGNATURE 314874dc87cd4676894cd03481a9ea22  
2019-08-15 03:25:40,908  SUCCESS get_fare_rules AIRLINE SIGNATURE 314874dc87cd4676894cd03481a9ea22  
2019-08-15 03:25:42,116  SUCCESS sell_journeys AIRLINE SIGNATURE 314874dc87cd4676894cd03481a9ea22  
2019-08-15 03:27:52,065  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:29:51,509  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:33:20,214  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:33:33,284  SIGNIN AIRLINE SUCCESS SIGNATURE d14fd10eb62341309fc9c1f5acee3ee6  
2019-08-15 03:33:34,030  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE d14fd10eb62341309fc9c1f5acee3ee6  
2019-08-15 03:36:18,838  get_balance SUCCESS SIGNATURE d14fd10eb62341309fc9c1f5acee3ee6  
2019-08-15 03:38:36,145  get_balance SUCCESS SIGNATURE d14fd10eb62341309fc9c1f5acee3ee6  
2019-08-15 03:40:27,139  SIGNIN AIRLINE SUCCESS SIGNATURE 015a29479a0b4c959c37b60a8b51646c  
2019-08-15 03:41:41,134  SIGNIN AIRLINE SUCCESS SIGNATURE 65dcb68fb0f64ad3ade65bd3b40967b2  
2019-08-15 03:42:10,801  SIGNIN AIRLINE SUCCESS SIGNATURE e38166a4d7e34b12a32b3600667201a9  
2019-08-15 03:42:52,659  SIGNIN AIRLINE SUCCESS SIGNATURE 338d6ce01f1c46f9a97fecafbfa85008  
2019-08-15 03:45:00,148  SIGNIN AIRLINE SUCCESS SIGNATURE 425819ad882e4aa4a6b16e897c32c2ad  
2019-08-15 03:45:00,371  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE 425819ad882e4aa4a6b16e897c32c2ad  
2019-08-15 03:46:38,776  SIGNIN AIRLINE SUCCESS SIGNATURE 209d4fea080a42c88e97ca40836b974a  
2019-08-15 03:47:06,545  SIGNIN AIRLINE SUCCESS SIGNATURE 1b0dfb34c4db4c7ba56af5f404dd935f  
2019-08-15 03:47:09,707  SIGNIN AIRLINE SUCCESS SIGNATURE 90e225942d404bbc8eddb6a5b2fec054  
2019-08-15 03:47:28,223  SIGNIN AIRLINE SUCCESS SIGNATURE dda12018f2d345c88e186e61a9fe1fbe  
2019-08-15 03:47:29,579  SIGNIN AIRLINE SUCCESS SIGNATURE c6d5751ee145421eb2ea755097257458  
2019-08-15 03:47:35,150  SIGNIN AIRLINE SUCCESS SIGNATURE 08c174d206e54a53ad20559428cb6875  
2019-08-15 03:47:37,849  SIGNIN AIRLINE SUCCESS SIGNATURE 3eacbf5430054a92a4d4b097c8d35f3c  
2019-08-15 03:47:41,503  SIGNIN AIRLINE SUCCESS SIGNATURE 8ac505c51d57415c9b0e8dd9957e7720  
2019-08-15 03:47:45,045  SIGNIN AIRLINE SUCCESS SIGNATURE 9588f61d7b244d7f983059b7371a9cc2  
2019-08-15 03:47:49,796  SIGNIN AIRLINE SUCCESS SIGNATURE 39cac14481324bd482230b7217230c8a  
2019-08-15 03:47:53,771  SIGNIN AIRLINE SUCCESS SIGNATURE 73b541fff64b4816bbe964578f74aa10  
2019-08-15 03:47:57,539  SIGNIN AIRLINE SUCCESS SIGNATURE 78fb0996786e4172905269dcb09bff1e  
2019-08-15 03:48:02,830  SIGNIN AIRLINE SUCCESS SIGNATURE fbe0979b82f74c089bea02045b0d4248  
2019-08-15 03:48:05,438  SIGNIN AIRLINE SUCCESS SIGNATURE 59de80c791a94f9ebfae552abb1e6c14  
2019-08-15 03:48:09,527  SIGNIN AIRLINE SUCCESS SIGNATURE c6658541061f42f58224981f91371bce  
2019-08-15 03:48:13,993  SIGNIN AIRLINE SUCCESS SIGNATURE 7bed3a8f81e64562bebce84d31a6bdc4  
2019-08-15 03:48:18,260  SIGNIN AIRLINE SUCCESS SIGNATURE 04d1a91b775e40f087416a8e0456abc2  
2019-08-15 03:48:22,335  SIGNIN AIRLINE SUCCESS SIGNATURE dfd58777add040ffacedb532caa146f8  
2019-08-15 03:48:25,876  SIGNIN AIRLINE SUCCESS SIGNATURE ed3b6fa656b042b0aff9c498b4dc7ef0  
2019-08-15 03:48:30,418  SIGNIN AIRLINE SUCCESS SIGNATURE 2dcc6612706842e5bde61a49626e626c  
2019-08-15 03:48:33,192  SIGNIN AIRLINE SUCCESS SIGNATURE 0ad826655e9047fb813769bdb7af9e1e  
2019-08-15 03:48:38,665  SIGNIN AIRLINE SUCCESS SIGNATURE 13a01bdf8c9843e681a2576aabc02f5c  
2019-08-15 03:48:41,069  SIGNIN AIRLINE SUCCESS SIGNATURE fbff9c7c498c4745b436d742d27ad735  
2019-08-15 03:48:45,177  SIGNIN AIRLINE SUCCESS SIGNATURE 21910ac3dcee4fe7960ed55b8ef87a9f  
2019-08-15 03:48:48,741  SIGNIN AIRLINE SUCCESS SIGNATURE ee0f6051149a4256b243df9f03e3a35a  
2019-08-15 03:48:52,846  SIGNIN AIRLINE SUCCESS SIGNATURE 168dfaa417654b0eaad80f9d43ea8c14  
2019-08-15 03:48:56,517  SIGNIN AIRLINE SUCCESS SIGNATURE e3dfdf9cf3284d1f870c5cec0e8ad6db  
2019-08-15 03:49:00,745  SIGNIN AIRLINE SUCCESS SIGNATURE ad5a709c56614c5b98805eaa582977d7  
2019-08-15 03:49:04,787  SIGNIN AIRLINE SUCCESS SIGNATURE 574b0535260a4dd0891c70efa18d48e1  
2019-08-15 03:49:10,315  SIGNIN AIRLINE SUCCESS SIGNATURE 5edeee155b90403aa7e1d13dbfab1002  
2019-08-15 03:49:14,145  SIGNIN AIRLINE SUCCESS SIGNATURE 5d2ac862418f4c8193195bc9664b4025  
2019-08-15 03:49:18,083  SIGNIN AIRLINE SUCCESS SIGNATURE eae894a448874aaf81a75b1d9615a415  
2019-08-15 03:49:21,138  SIGNIN AIRLINE SUCCESS SIGNATURE f8452d5c929547839958a9b8fb1e3e49  
2019-08-15 03:49:25,848  SIGNIN AIRLINE SUCCESS SIGNATURE 4f839b367032459aa0c564df0179bf9e  
2019-08-15 03:49:29,912  SIGNIN AIRLINE SUCCESS SIGNATURE 19931a9a2ef443329fb626a96ac4090d  
2019-08-15 03:49:37,368  SIGNIN AIRLINE SUCCESS SIGNATURE 3cbfd67208a844cda1964c946251ed76  
2019-08-15 03:49:38,467  SIGNIN AIRLINE SUCCESS SIGNATURE 24c14e76ed1b48aab13063f7464f23f6  
2019-08-15 03:49:41,548  SIGNIN AIRLINE SUCCESS SIGNATURE 116cc87bd50f4959b31a21c377ba154f  
2019-08-15 03:49:45,563  SIGNIN AIRLINE SUCCESS SIGNATURE 26b05f75dfc54c2c801ad16f2a927e04  
2019-08-15 03:49:49,729  SIGNIN AIRLINE SUCCESS SIGNATURE 2aa4423482d24199b8e9a69b5a52454c  
2019-08-15 03:49:53,687  SIGNIN AIRLINE SUCCESS SIGNATURE 77168862ee0447fc9c4f190825a8c917  
2019-08-15 03:49:57,283  SIGNIN AIRLINE SUCCESS SIGNATURE e78cdee237d3427193f405b8ba85348e  
2019-08-15 03:50:01,891  SIGNIN AIRLINE SUCCESS SIGNATURE 0d0a0eb306024102b845715fcc96cd3e  
2019-08-15 03:50:02,482  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE 0d0a0eb306024102b845715fcc96cd3e  
2019-08-15 03:50:04,886  SIGNIN AIRLINE SUCCESS SIGNATURE 5055bfe339ca4af0bd2694ab004fb83f  
2019-08-15 03:50:08,989  SIGNIN AIRLINE SUCCESS SIGNATURE 632f12c1a5d7453f904b43deb0053de3  
2019-08-15 03:50:12,190  SIGNIN AIRLINE SUCCESS SIGNATURE 864b835c965949d3884c003c0f6e0cab  
2019-08-15 03:50:16,045  SIGNIN AIRLINE SUCCESS SIGNATURE 3fe6129c21eb4cabb45141a42dacbcdf  
2019-08-15 03:50:20,512  SIGNIN AIRLINE SUCCESS SIGNATURE 27c0d3ee5c1c41d29d92f8385d1d0dd4  
2019-08-15 03:50:24,012  SIGNIN AIRLINE SUCCESS SIGNATURE 38115d84f1f645c1a48888e3db289644  
2019-08-15 03:50:28,046  SIGNIN AIRLINE SUCCESS SIGNATURE 0a14e1243a7c4cd0855f973e3807762b  
2019-08-15 03:50:32,773  SIGNIN AIRLINE SUCCESS SIGNATURE 1f465c99e77a46a3a24c52948a94ab8b  
2019-08-15 03:50:35,663  SIGNIN AIRLINE SUCCESS SIGNATURE 4fb527fe46ef49eeae3f4e1b5bb7854a  
2019-08-15 03:50:40,990  SIGNIN AIRLINE SUCCESS SIGNATURE 22581326f71a4c1a8bd777faeba4b3a0  
2019-08-15 03:50:43,374  SIGNIN AIRLINE SUCCESS SIGNATURE 1861975b37aa4468b2ffc8d118f6b8a7  
2019-08-15 03:50:48,960  SIGNIN AIRLINE SUCCESS SIGNATURE f295371fcab74c4c85e82ec9d3bc7b9c  
2019-08-15 03:50:51,210  SIGNIN AIRLINE SUCCESS SIGNATURE 9004aee447a04ba98e12dcd66f45ff08  
2019-08-15 03:50:56,937  SIGNIN AIRLINE SUCCESS SIGNATURE cf50a1acdf4d421886cf098f7181d636  
2019-08-15 03:50:59,449  SIGNIN AIRLINE SUCCESS SIGNATURE 5e46f7c2d0c94832870a25b53e9832a8  
2019-08-15 03:51:03,294  SIGNIN AIRLINE SUCCESS SIGNATURE 9e97ca89c9614469a7be4ab1ad436c4e  
2019-08-15 03:51:08,107  SIGNIN AIRLINE SUCCESS SIGNATURE e3fc83d9533a408482df5c67a844ce4d  
2019-08-15 03:51:21,402  SIGNIN AIRLINE SUCCESS SIGNATURE e856f09ccd9d4ce385692e49b48ef235  
2019-08-15 03:51:22,443  SIGNIN AIRLINE SUCCESS SIGNATURE d2beaeed063a4bf6a0982917a6853918  
2019-08-15 03:51:33,720  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 03:52:44,064  SIGNIN AIRLINE SUCCESS SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 03:52:59,755  ERROR SEARCH AIRLINE SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 03:52:59,758  ERROR SEARCH AIRLINE SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 03:52:59,773  ERROR SEARCH AIRLINE SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 03:53:00,816  ERROR SEARCH AIRLINE SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 03:53:00,834  ERROR SEARCH AIRLINE SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 03:53:00,836  ERROR SEARCH AIRLINE SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 03:55:44,230  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 93, in get_balance
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 03:58:14,254  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 93, in get_balance
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 04:00:45,225  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 93, in get_balance
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 04:02:54,096  get_balance SUCCESS SIGNATURE 85157dcc1e1346b999574db6efef07e4  
2019-08-15 04:03:21,621  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 04:03:52,982  SIGNIN AIRLINE SUCCESS SIGNATURE 770eb0b6c43146849156c8082b5d3b49  
2019-08-15 04:04:24,311  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 134, in login
    request.session['airline_signature'] = res['result']['response']['signature']
KeyError: 'result'
  
2019-08-15 04:05:55,609  SIGNIN AIRLINE SUCCESS SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:05:59,701  ERROR SEARCH AIRLINE SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:06:00,394  ERROR SEARCH AIRLINE SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:06:02,213  ERROR SEARCH AIRLINE SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:06:21,053  ERROR SEARCH AIRLINE SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:06:24,686  ERROR SEARCH AIRLINE SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:08:04,888  get_balance SUCCESS SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:11:05,734  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_account_views.py", line 93, in get_balance
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 04:13:08,851  get_balance SUCCESS SIGNATURE 024f454a66264fd78982e6f08aa89ce6  
2019-08-15 04:16:22,074  get_carriers AIRLINE ERROR USE CACHE SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 04:19:19,907  SIGNIN AIRLINE SUCCESS SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:19,994  get_carrier_providers AIRLINE RENEW SUCCESS SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:20,718  ERROR SEARCH AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:20,735  ERROR SEARCH AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:20,746  ERROR SEARCH AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:21,024  ERROR SEARCH AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:21,064  ERROR SEARCH AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:21,064  ERROR SEARCH AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:31,646  SUCCESS get_price_itinerary AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:36,753  SUCCESS sell_journeys AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:19:37,856  SUCCESS get_fare_rules AIRLINE SIGNATURE 1dcca5899e7e48d486d911252fbce46a  
2019-08-15 04:31:09,230  SIGNIN AIRLINE SUCCESS SIGNATURE f1da000b869e41d6a6520d58ae5aaf9a  
2019-08-15 04:31:10,457  ERROR SEARCH AIRLINE SIGNATURE f1da000b869e41d6a6520d58ae5aaf9a  
2019-08-15 04:31:10,615  ERROR SEARCH AIRLINE SIGNATURE f1da000b869e41d6a6520d58ae5aaf9a  
2019-08-15 04:31:10,838  ERROR SEARCH AIRLINE SIGNATURE f1da000b869e41d6a6520d58ae5aaf9a  
2019-08-15 04:31:11,222  ERROR SEARCH AIRLINE SIGNATURE f1da000b869e41d6a6520d58ae5aaf9a  
2019-08-15 04:31:11,247  ERROR SEARCH AIRLINE SIGNATURE f1da000b869e41d6a6520d58ae5aaf9a  
2019-08-15 04:31:13,975  SIGNIN AIRLINE SUCCESS SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
2019-08-15 04:31:15,457  ERROR SEARCH AIRLINE SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
2019-08-15 04:31:16,005  ERROR SEARCH AIRLINE SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
2019-08-15 04:31:16,336  ERROR SEARCH AIRLINE SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
2019-08-15 04:31:16,511  ERROR SEARCH AIRLINE SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
2019-08-15 04:31:28,536  SUCCESS get_price_itinerary AIRLINE SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
2019-08-15 04:31:35,275  SUCCESS sell_journeys AIRLINE SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
2019-08-15 04:31:36,776  SUCCESS get_fare_rules AIRLINE SIGNATURE 0ca6bbe15ed24739970a781efd3a9254  
