2019-08-15 01:05:08,138  SIGNIN SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:08,211  USE CACHE IN TXT!  
2019-08-15 01:05:09,227  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:09,326  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:48,728  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:48,933  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:05:50,535  SIGNIN AIRLINE SUCCESS SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:06,572  SUCCESS get_price_itinerary AIRLINE SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:12,572  SUCCESS get_fare_rules AIRLINE SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:13,127  SUCCESS sell_journeys AIRLINE SIGNATURE 7db5432f4a5d4eb190d3a69437a2e36d  
2019-08-15 01:06:27,492  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:06:27,561  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:06:28,397  SIGNIN AIRLINE SUCCESS SIGNATURE 64ee40a68cd74b9588c5942c7aa3ef85  
2019-08-15 01:07:05,143  SUCCESS get_price_itinerary AIRLINE SIGNATURE 64ee40a68cd74b9588c5942c7aa3ef85  
2019-08-15 01:07:11,721  SUCCESS get_fare_rules AIRLINE SIGNATURE 64ee40a68cd74b9588c5942c7aa3ef85  
2019-08-15 01:08:34,876  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:08:34,946  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:08:35,624  SIGNIN AIRLINE SUCCESS SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:08:50,523  SUCCESS get_price_itinerary AIRLINE SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:08:59,265  SUCCESS sell_journeys AIRLINE SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:09:01,928  SUCCESS get_fare_rules AIRLINE SIGNATURE 22f04adfd576476b97b6bd7101b6a466  
2019-08-15 01:10:34,315  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:34,539  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:35,093  SIGNIN AIRLINE SUCCESS SIGNATURE 7eb7f12977ad46bb9c7a42958eb88b7b  
2019-08-15 01:10:52,144  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:52,436  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:10:52,953  SIGNIN AIRLINE SUCCESS SIGNATURE 793381fc69d4430383d96ff13395195b  
2019-08-15 01:12:13,662  get_balance SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:12:13,892  get_transactions SUCCESS SIGNATURE ec62f39910144c9aab4120ce68425d05  
2019-08-15 01:12:14,373  SIGNIN AIRLINE SUCCESS SIGNATURE 46b3f3bbe85c4f5a949dff45d2fb86fd  
2019-08-15 01:14:22,721  SIGNIN SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:22,769  USE CACHE IN TXT!  
2019-08-15 01:14:26,022  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:26,313  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:41,186  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:41,387  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:41,613  SIGNIN AIRLINE SUCCESS SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,389  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,406  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,546  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,563  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,675  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:42,913  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:43,008  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:43,056  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:43,063  ERROR SEARCH AIRLINE SIGNATURE f76336d9fddd49e9aa3a5e93ced73674  
2019-08-15 01:14:49,909  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:50,068  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:14:51,131  SIGNIN AIRLINE SUCCESS SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:06,725  SUCCESS get_price_itinerary AIRLINE SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:14,195  SUCCESS sell_journeys AIRLINE SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:21,170  SUCCESS get_fare_rules AIRLINE SIGNATURE 35a80896dadf4a17bffbbebb5f330032  
2019-08-15 01:15:53,214  SIGNIN AIRLINE SUCCESS SIGNATURE 27bf33517437483d93eff1aad19f15ae  
2019-08-15 01:15:53,215  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:53,337  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:55,580  get_balance SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:55,639  get_transactions SUCCESS SIGNATURE bd9507381f96498cb824c6fe080003d8  
2019-08-15 01:15:55,736  SIGNIN AIRLINE SUCCESS SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:16:23,494  SUCCESS get_price_itinerary AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:16:23,521  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,545  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,566  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,587  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,609  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,629  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,647  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,665  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,683  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,704  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,724  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,742  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,757  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,771  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,786  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,801  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,816  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,830  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,842  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,853  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,866  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,878  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,887  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,899  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,912  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,920  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,932  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,947  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,955  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,965  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:16:23,976  'result'
Traceback (most recent call last):
  File "/Users/GSCAdi/Documents/rodextrip/tt_webservice/views/tt_webservice_airline_views.py", line 447, in get_price_itinerary
    if res['result']['error_code'] == 0:
KeyError: 'result'
  
2019-08-15 01:17:07,768  SUCCESS get_price_itinerary AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:17:14,043  SUCCESS get_fare_rules AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:17:51,210  SUCCESS sell_journeys AIRLINE SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
2019-08-15 01:18:20,847  get_balance SUCCESS SIGNATURE 9c37ca0badda4e00a95756ac6909e1c2  
